python ../../veil_switch.pyc fat-tree-k2.adlist fat-tree-k2.vid localhost:4001 0 &
python ../../veil_switch.pyc fat-tree-k2.adlist fat-tree-k2.vid localhost:4002 0 &
python ../../veil_switch.pyc fat-tree-k2.adlist fat-tree-k2.vid localhost:4003 0 &
python ../../veil_switch.pyc fat-tree-k2.adlist fat-tree-k2.vid localhost:4004 0 &
python ../../veil_switch.pyc fat-tree-k2.adlist fat-tree-k2.vid localhost:2001 0 &
python ../../veil_switch.pyc fat-tree-k2.adlist fat-tree-k2.vid localhost:2002 0 &
python ../../veil_switch.pyc fat-tree-k2.adlist fat-tree-k2.vid localhost:2003 0 &
python ../../veil_switch.pyc fat-tree-k2.adlist fat-tree-k2.vid localhost:2004 0 &
python ../../veil_switch.pyc fat-tree-k2.adlist fat-tree-k2.vid localhost:2005 0 &
python ../../veil_switch.pyc fat-tree-k2.adlist fat-tree-k2.vid localhost:2006 0 &
python ../../veil_switch.pyc fat-tree-k2.adlist fat-tree-k2.vid localhost:2007 0 &
python ../../veil_switch.pyc fat-tree-k2.adlist fat-tree-k2.vid localhost:2008 0 &
python ../../veil_switch.pyc fat-tree-k2.adlist fat-tree-k2.vid localhost:3001 0 &
python ../../veil_switch.pyc fat-tree-k2.adlist fat-tree-k2.vid localhost:3002 0 &
python ../../veil_switch.pyc fat-tree-k2.adlist fat-tree-k2.vid localhost:3003 0 &
python ../../veil_switch.pyc fat-tree-k2.adlist fat-tree-k2.vid localhost:3004 0 &
python ../../veil_switch.pyc fat-tree-k2.adlist fat-tree-k2.vid localhost:3005 0 &
python ../../veil_switch.pyc fat-tree-k2.adlist fat-tree-k2.vid localhost:3006 0 &
python ../../veil_switch.pyc fat-tree-k2.adlist fat-tree-k2.vid localhost:3007 0 &
python ../../veil_switch.pyc fat-tree-k2.adlist fat-tree-k2.vid localhost:3008 0 & 

