python ../../veil_switch.pyc isp-level3.adlist isp-level3.vid localhost:8001 0 > 0.runshout &
python ../../veil_switch.pyc isp-level3.adlist isp-level3.vid localhost:8002 0 > 1.runshout &
python ../../veil_switch.pyc isp-level3.adlist isp-level3.vid localhost:8003 0 > 2.runshout &
python ../../veil_switch.pyc isp-level3.adlist isp-level3.vid localhost:8004 0 > 3.runshout &
python ../../veil_switch.pyc isp-level3.adlist isp-level3.vid localhost:8005 0 > 4.runshout &
python ../../veil_switch.pyc isp-level3.adlist isp-level3.vid localhost:8006 0 > 5.runshout &
python ../../veil_switch.pyc isp-level3.adlist isp-level3.vid localhost:8007 0 > 6.runshout &
python ../../veil_switch.pyc isp-level3.adlist isp-level3.vid localhost:8008 0 > 7.runshout &
python ../../veil_switch.pyc isp-level3.adlist isp-level3.vid localhost:8009 0 > 8.runshout &
python ../../veil_switch.pyc isp-level3.adlist isp-level3.vid localhost:8010 0 > 9.runshout &
python ../../veil_switch.pyc isp-level3.adlist isp-level3.vid localhost:8011 0 > 10.runshout &
python ../../veil_switch.pyc isp-level3.adlist isp-level3.vid localhost:8012 0 > 11.runshout &
python ../../veil_switch.pyc isp-level3.adlist isp-level3.vid localhost:8013 0 > 12.runshout &
python ../../veil_switch.pyc isp-level3.adlist isp-level3.vid localhost:8014 0 > 131.runshout &
python ../../veil_switch.pyc isp-level3.adlist isp-level3.vid localhost:8015 0 > 14.runshout &
python ../../veil_switch.pyc isp-level3.adlist isp-level3.vid localhost:8016 0 > 15.runshout &
python ../../veil_switch.pyc isp-level3.adlist isp-level3.vid localhost:8017 0 > 16.runshout &
python ../../veil_switch.pyc isp-level3.adlist isp-level3.vid localhost:8018 0 > 17.runshout &
python ../../veil_switch.pyc isp-level3.adlist isp-level3.vid localhost:8019 0 > 18.runshout &
python ../../veil_switch.pyc isp-level3.adlist isp-level3.vid localhost:8020 0 > 19.runshout &
python ../../veil_switch.pyc isp-level3.adlist isp-level3.vid localhost:8021 0 > 20.runshout &
python ../../veil_switch.pyc isp-level3.adlist isp-level3.vid localhost:8022 0 > 21.runshout &
python ../../veil_switch.pyc isp-level3.adlist isp-level3.vid localhost:8023 0 > 22.runshout &
python ../../veil_switch.pyc isp-level3.adlist isp-level3.vid localhost:8024 0 > 23.runshout &
python ../../veil_switch.pyc isp-level3.adlist isp-level3.vid localhost:8025 0 > 24.runshout &
python ../../veil_switch.pyc isp-level3.adlist isp-level3.vid localhost:8026 0 > 25.runshout &
python ../../veil_switch.pyc isp-level3.adlist isp-level3.vid localhost:8027 0 > 26.runshout &
python ../../veil_switch.pyc isp-level3.adlist isp-level3.vid localhost:8028 0 > 27.runshout &
python ../../veil_switch.pyc isp-level3.adlist isp-level3.vid localhost:8029 0 > 28.runshout &
python ../../veil_switch.pyc isp-level3.adlist isp-level3.vid localhost:8030 0 > 29.runshout &
python ../../veil_switch.pyc isp-level3.adlist isp-level3.vid localhost:8031 0 > 30.runshout &
python ../../veil_switch.pyc isp-level3.adlist isp-level3.vid localhost:8032 0 > 31.runshout &
python ../../veil_switch.pyc isp-level3.adlist isp-level3.vid localhost:8033 0 > 32.runshout & 

